#!/home/mgorny/bin/run-cronjob.sh

set -e -x
ulimit -t 600 -v 2097152

. /home/mgorny/pkgcore-venv/bin/activate

sync=/home/mgorny/sync/gentoo
pull=/home/mgorny/pull

cd "${sync}"
git fetch https://github.com/gentoo/gentoo 'refs/pull/*/head:refs/pull/*'

mkdir -p "${pull}"
while read hash t ref; do
	prid=${ref#refs/pull/}

	echo "${hash}" > "${pull}/${prid}"
done < <(git for-each-ref 'refs/pull/*')
