#!/home/mgorny/bin/run-cronjob.sh
# vim:ft=sh

set -e -x
ulimit -t 600 -v 2097152

. "${VIRTUAL_ENV}"/bin/activate

"${SCRIPT_DIR}"/update-repos.py
cd "${LOG_DIR}"
dates=( * )

"${SCRIPT_DIR}"/update-mirror.py "${dates[-1]}"/summary.json \
	"${dates[-1]}"/repositories.xml > "${MIRROR_DIR}"/Makefile.repos
"${SCRIPT_DIR}"/publish-logs.sh "${dates[-1]}"

make -C "${MIRROR_DIR}" clean
make -j16 -k -C "${MIRROR_DIR}"
