#!/home/mgorny/bin/run-cronjob.sh

set -e -x
ulimit -t 600 -v 2097152

. /home/mgorny/pkgcore-venv/bin/activate

cd /home/mgorny
/home/mgorny/bin/update-repos.py
cd log
dates=( * )

/home/mgorny/bin/update-mirror.py "${dates[-1]}"/summary.json "${dates[-1]}"/repositories.xml > /home/mgorny/mirror/Makefile.repos
/home/mgorny/bin/publish-logs.sh ${dates[-1]}

make -C /home/mgorny/mirror clean
make -j16 -k -C /home/mgorny/mirror
