#!/bin/bash

merge_subrepo() {
	url=${1}
	path=${2}
	branch=${3:-master}

	if [[ ! -d ${path} ]]; then
		git subtree add --prefix="${path}" "${url}" "${branch}"
	else
		git subtree pull --prefix="${path}" "${url}" "${branch}"
	fi
}

fetch_file() {
	url=${1}
	dir=${2}

	wget -P "${dir}" -N "${url}"
}

set -e -x

cd "${1}"
merge_subrepo git://anongit.gentoo.org/data/dtd.git metadata/dtd
merge_subrepo git://anongit.gentoo.org/data/glsa.git metadata/glsa
merge_subrepo git://anongit.gentoo.org/data/gentoo-news.git metadata/news
merge_subrepo git://anongit.gentoo.org/data/xml-schema.git metadata/xml-schema
fetch_file https://api.gentoo.org/metastructure/projects.xml metadata/

# set appropriate remotes if we're working off fresh clone
if [[ -z $(git config --get remote.gentoo.url) ]]; then
	git remote add gentoo git@git.gentoo.org:repo/sync/gentoo.git
	git remote add github git@github.com:gentoo-mirror/gentoo
	git config --add remote.origin.pushurl git@github.com:gentoo-mirror/gentoo
	git config --add remote.origin.pushurl git@git.gentoo.org:repo/sync/gentoo.git
fi
