#!/bin/bash

merge_subrepo() {
	url=${1}
	path=${2}
	branch=${3:-master}

	if [[ ! -d ${path} ]]; then
		git subtree add --prefix="${path}" "${url}" "${branch}"
	else
		git subtree pull --prefix="${path}" "${url}" "${branch}"
	fi
}

fetch_file() {
	url=${1}
	dir=${2}

	wget -P "${dir}" -N "${url}"
}

set -e -x

cd "${1}"
merge_subrepo git://anongit.gentoo.org/data/dtd.git metadata/dtd
merge_subrepo git://anongit.gentoo.org/data/glsa.git metadata/glsa
merge_subrepo git://anongit.gentoo.org/data/gentoo-news.git metadata/news
merge_subrepo git://anongit.gentoo.org/data/xml-schema.git metadata/xml-schema
fetch_file https://api.gentoo.org/metastructure/projects.xml metadata/
