#!/bin/bash

every_hrs() {
	hrs=${1}
	shift

	cmd=${*}
	tag=${cmd//[ :.\/]/_}
	now=$(date +%s)
	last=$(<".git/last-${tag}") || last=0

	if [[ $((now - last )) -ge $((hrs * 3600)) ]]; then
		"${@}"
		echo "${now}" > ".git/last-${tag}"
	fi
}

merge_subrepo() {
	url=${1}
	path=${2}
	branch=${3:-master}

	if [[ ! -d ${path} ]]; then
		git subtree add --prefix="${path}" "${url}" "${branch}"
	else
		git subtree pull --prefix="${path}" "${url}" "${branch}"
	fi
}

fetch_file() {
	url=${1}
	dir=${2}

	wget -P "${dir}" -N "${url}"
}

set -e -x

cd "${1}"
export EDITOR=cat
every_hrs 24 merge_subrepo git@git.gentoo.org:data/dtd.git metadata/dtd
merge_subrepo git@git.gentoo.org:data/glsa.git metadata/glsa
every_hrs 6 merge_subrepo git@git.gentoo.org:data/gentoo-news.git metadata/news
every_hrs 24 merge_subrepo git@git.gentoo.org:data/xml-schema.git metadata/xml-schema
every_hrs 6 fetch_file https://api.gentoo.org/metastructure/projects.xml metadata/

# set appropriate remotes if we're working off fresh clone
if [[ -z $(git config --get remote.gentoo.url) ]]; then
	git remote add gentoo git@git.gentoo.org:repo/sync/gentoo.git
	git remote add github git@github.com:gentoo-mirror/gentoo
	git config --add remote.origin.pushurl git@github.com:gentoo-mirror/gentoo
	git config --add remote.origin.pushurl git@git.gentoo.org:repo/sync/gentoo.git
fi

# verify the OpenPGP signature again after smart-merge
[[ $(git show -q --pretty=format:'%G?' orig/master) == [GU] ]]
# and enable git commit signing
git config commit.gpgsign 1
